# Generated by Django 5.1.3 on 2024-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorical_features', models.JSONField()),
                ('numeric_features', models.JSONField()),
                ('date_features', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('learning_rate', models.FloatField()),
                ('max_iter', models.IntegerField()),
                ('max_leaf_nodes', models.IntegerField()),
                ('min_samples_leaf', models.IntegerField()),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('confusion_matrix', models.JSONField()),
                ('classification_report', models.JSONField()),
                ('feature_importance', models.JSONField()),
            ],
        ),
    ]
